// USER Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

// EMPLOYEE Reducer Types
export const EMPLOYEE_LIST_LOADING = 'EMPLOYEE_LIST_LOADING';
export const EMPLOYEE_LIST_LOADED = 'EMPLOYEE_LIST_LOADED';

// UI Reducer Types
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
